name: KBOT-CICD

on:
  push:
    branches:
      - develop

env:
  TARGETARCH: amd64
  TARGETOS: linux
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: make test

      - name: GHCR login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: pavlenkoua
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        env:
          APP: "kbot"
          REGISTRY: ghcr.io
          USERNAME: ${{ secrets.GHCR_USERNAME }}
          TOKEN: ${{ secrets.GHCR_TOKEN }}
          TARGETOS: ${{ env.TARGETOS }}
        run: make image push TARGETARCH=$TARGETARCH TARGETOS=$TARGETOS 
      
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=env(VERSION) | .image.arch=env(TARGETARCH)' helm/values.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "Update version to $VERSION"
        git push